blueprint:
  name: Extinction de la prise une fois le téléphone chargé
  description: Éteignez la prise connectée une fois que l'appareil est chargé à un pourcentage donné.
  domain: automation
  input:
    switch:
      name: Prise connectée
      description: Prise connectée à éteindre
      selector:
        entity:
          domain: switch

    phone_battery:
      name: Batterie du téléphone
      description: Capteur du pourcentage de la batterie du téléphone
      selector:
        entity:
          domain: sensor
          device_class: battery

    charged_percent:
      name: Pourcentage à atteindre
      description: Pourcentage que la batterie doit atteindre
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: "box"
      default: 100

variables:
  phone_battery: !input phone_battery
  charged_percent: !input charged_percent

trigger:
  - platform: state
    entity_id: !input phone_battery

condition:
  condition: template
  value_template: "{{ (states(phone_battery)|int) >= (charged_percent|int) }}"

action:
  - service: switch.turn_off
    entity_id: !input switch
